/**
 * OnlyFans Secrets – all 7 chapters (recreated from onlyfanssecrets.netlify.app).
 * By Adin Zander.
 */

export interface ChapterBlock {
  type: 'p' | 'h3' | 'blockquote' | 'ul';
  text?: string;
  items?: string[];
}

export interface Chapter {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  takeaways: string[];
  blocks: ChapterBlock[];
}

export const ONLYFANS_SECRETS_INTRO = {
  title: 'OnlyFans Secrets',
  subtitle: 'Learn how to build a successful OnlyFans business through personal branding, strategic content, and authentic connection—not just sexy pictures.',
  byline: 'By Adin Zander',
};

export const ONLYFANS_SECRETS_CHAPTERS: Chapter[] = [
  {
    id: 'why-personal-branding',
    number: 1,
    title: 'Why Personal Branding > Posting Sexy Pics',
    subtitle: 'Discover why building a personal brand is more powerful than just posting attractive content.',
    takeaways: [
      'Personal branding creates lasting value beyond individual posts',
      'Strong brands command premium prices and loyal fans',
      'Branding differentiates you in a crowded market',
    ],
    blocks: [
      { type: 'p', text: "Let's get one thing straight: hot content will always get attention. But attention isn't the same thing as loyalty, trust, or income that grows over time." },
      { type: 'p', text: "Sexy pics can go viral. A spicy clip might even land you a few paying subs. But what happens when someone hotter, younger, or more extreme pops up tomorrow?" },
      { type: 'p', text: 'They leave.' },
      { type: 'p', text: "The creators who win long-term are the ones who know this truth: If all you are is sexy, you're easy to replace. But if people feel connected to you, they'll pay just to be close." },
      { type: 'h3', text: 'The New Game: Attention with Attachment' },
      { type: 'p', text: "Your goal as a creator isn't just to be watched — it's to be missed when you're gone. It's to make people check your page not just because of your body, but because they feel invested in you. They're curious about your life. They want to feel like they're part of your world." },
      { type: 'p', text: 'That\'s what personal branding does. It builds a version of "you" that people can: Get emotionally attached to, Feel like they\'re discovering more of over time, Want to pay to be closer to' },
      { type: 'p', text: "And the best part? It works whether you're a beginner or already have subs — because branding upgrades how people see you." },
      { type: 'h3', text: "Why Sexy Alone Isn't Enough" },
      { type: 'p', text: 'Imagine you post a fire bikini pic on Instagram and drop your OnlyFans link in the bio. You get likes. A few DMs. Maybe even a sub or two. Cool. But a week later, your views are down again. Why?' },
      { type: 'p', text: "Because you didn't give them a reason to stay." },
      { type: 'p', text: "Here's what gets lost when you only focus on sex appeal: You attract low-quality followers who just want free stuff, You look like every other creator in their feed, You have no long-term strategy or growth, You're building a business on \"hope,\" not intention" },
      { type: 'h3', text: 'Branding Turns You Into a Character They Want More Of' },
      { type: 'p', text: 'When you build a brand, you stop being just "hot girl online" and start becoming a story. Think about people like: The Kardashians, Lana Rhoades, Bella Thorne, Corinna Kopf' },
      { type: 'p', text: "They built audiences not just through sex appeal, but through personality, drama, lifestyle, mystery, and storytelling." },
      { type: 'p', text: 'Even when they\'re not nude, people still watch. Why? Because they\'ve become characters people care about. Your face, your vibe, your daily life — all of that becomes the content. And the mystery of "what\'s she like behind the scenes?" leads them to your private world (Snapchat) and finally to OnlyFans.' },
      { type: 'h3', text: 'The "Brand First" Mindset' },
      { type: 'p', text: 'Every piece of content you put out — from a coffee selfie to a vlog about your weekend — is a chance to build your brand.' },
      { type: 'p', text: "Here's what a personal brand does: Makes people remember you, Gives your content context (you're more than a body), Creates emotional attachment, Makes people feel like they know you, Makes followers want to see the uncut version (OnlyFans)" },
      { type: 'p', text: "And here's the key: Your personality becomes the tease. Your real life becomes the hook. And your Snapchat/OnlyFans becomes the reward." },
    ],
  },
  {
    id: 'kardashians-branding',
    number: 2,
    title: 'What the Kardashians Understand About Branding',
    subtitle: 'Learn the branding strategies that made the Kardashians billionaires and how to apply them to your OnlyFans.',
    takeaways: [
      'Consistency in aesthetic and messaging builds brand recognition',
      'Aspirational lifestyle content creates emotional connections',
      'Strategic visibility and conversation drive engagement',
    ],
    blocks: [
      { type: 'p', text: "You might love them, hate them, or never watch a single episode — but you know them. That's the power of branding." },
      { type: 'p', text: "The Kardashians didn't become billionaires by being the hottest women online. They became icons because they understood something deeper: People don't pay to see bodies. They pay to feel connected to someone they think they know." },
      { type: 'p', text: "Let's break down exactly what they do — and how you can apply it to build your own personal brand funnel." },
      { type: 'h3', text: '1. They Sell the Illusion of Access' },
      { type: 'p', text: 'You feel like you know Kim, Kylie, and Khloe. You\'ve seen them fight, cry, laugh, eat, get cheated on, bounce back. You\'ve followed their "real life" — even though it\'s 100% curated. That\'s the trick.' },
      { type: 'p', text: "The Kardashians strategically document their lives to make you feel like you're in their world. You're not buying a product — you're buying proximity." },
      { type: 'p', text: 'You can do the same. Your version of "Keeping Up With Me" might be vlogs, coffee shop check-ins, or gym selfies. They don\'t need to be explicit — they need to feel personal.' },
      { type: 'p', text: 'YouTube = daily vlog, Facebook = short clips from the vlog, Instagram = aesthetic lifestyle moments, Snapchat = raw, unfiltered "closer access", OnlyFans = behind the curtain (invite-only from Snap)' },
      { type: 'p', text: "You build curiosity, then filter the attention through your funnel. This gives your OnlyFans power — it's not spammed everywhere, it's earned." },
      { type: 'h3', text: '2. They Never Sell Too Early' },
      { type: 'p', text: "One thing the Kardashians never do: shove sales in your face all the time. They build trust. They show life. They let people get emotionally invested before they pitch. PG content comes first. Mystery builds second. Only THEN do they drop the offer." },
      { type: 'p', text: 'For you, that means: Don\'t pitch until they\'re curious.' },
      { type: 'h3', text: '3. They Are the Brand' },
      { type: 'p', text: "Every Kardashian is the brand. They don't just promote things — they become the product. Your goal is the same. People don't follow you because of what you sell. They follow you because you're you. Your look. Your vibe. Your chaos. Your energy." },
      { type: 'p', text: "You become the lifestyle people crave. Then they want the unfiltered version of it. And that's what leads them to Snapchat… and finally, OnlyFans." },
      { type: 'h3', text: '4. They Stay Consistent' },
      { type: 'p', text: "The Kardashians never disappear. There's always something new, even if it's just a glam photo or a random tweet. They've built the habit of being seen." },
      { type: 'p', text: "You don't have to post every hour — but you do need to show up consistently. That means: Weekly YouTube vlogs, Daily Instagram or story updates, 2–3 Facebook reels per week, Snapchat updates 2–5x per day" },
      { type: 'p', text: 'Consistency builds familiarity. Familiarity builds trust. And trust makes people pay.' },
      { type: 'h3', text: '5. They Let Their Audience Do the Marketing' },
      { type: 'p', text: "The Kardashians don't beg people to buy. Their fans share, repost, and hype them up nonstop. Why? Because they've created a brand that makes people feel proud to follow." },
      { type: 'p', text: 'You can do the same by: Naming your followers (like a tribe), Including fan shoutouts in your vlog, Creating inside jokes or "catchphrases", Making people feel like they\'re part of your world' },
      { type: 'p', text: "Let your fans be your best promoters — it's free, powerful, and authentic." },
    ],
  },
  {
    id: 'pg13-to-paid-funnel',
    number: 3,
    title: 'Your New Funnel: PG-13 to Paid',
    subtitle: 'Master the funnel that converts free followers into paying subscribers without being pushy or salesy.',
    takeaways: [
      'Start with PG-13 content to build curiosity and brand identity',
      'Create a bridge platform (like Snapchat) for more exclusive content',
      'Guide followers naturally to paid subscriptions without hard selling',
    ],
    blocks: [
      { type: 'p', text: "You're not just another creator trying to get subs. You're building a system — a funnel that takes strangers from casual viewers to obsessed followers, then into loyal paying fans on OnlyFans." },
      { type: 'p', text: 'Here\'s the truth: Most OnlyFans creators are screaming "subscribe!" without giving people a reason to care. You\'re going to build curiosity, connection, and desire — before they ever see your link.' },
      { type: 'h3', text: 'The Big Picture: Your 4-Step Funnel' },
      { type: 'p', text: 'Your content funnel has 4 key stages: 1. Public Lifestyle (PG-13), 2. Personal Connection (Snapchat), 3. Private Tease (DMs), 4. Premium Access (OnlyFans)' },
      { type: 'p', text: "Each level filters the audience further. You're not chasing them — they're choosing to come deeper into your world. Let's break it down." },
      { type: 'h3', text: 'Step 1: Public Lifestyle (PG-13)' },
      { type: 'p', text: 'Platforms: YouTube, Instagram, Facebook, TikTok' },
      { type: 'p', text: "This is your storefront. It's where people find you and decide if they want to keep watching. You're documenting your real life: Going to the gym, Getting coffee, Talking in your car, Shopping hauls, Trying on cute outfits (without being NSFW)" },
      { type: 'p', text: 'Think: flirty, stylish, aesthetic, vibey — but not sexual. Don\'t: mention OnlyFans, drop links, or push people to subscribe.' },
      { type: 'p', text: 'This builds intrigue and trust. They\'re thinking: "Who is she? She\'s hot, but she seems so chill. I want to see more…" Perfect. Now we move them closer.' },
      { type: 'h3', text: 'Step 2: Personal Connection (Snapchat)' },
      { type: 'p', text: "This is where the magic happens. Once someone's curious, you drop your Snapchat name in your IG stories or captions: \"If you want to see the real me, add me on Snap 👻\" type captions" },
      { type: 'p', text: "Snapchat feels more intimate. People know it's where things get a little messier, a little sexier, and a lot more personal." },
      { type: 'p', text: 'What you post here: Behind-the-scenes content, Risqué selfies, Bedroom mirror pics, Raw daily updates ("just woke up" energy), Light teasing, but still not full nudity' },
      { type: 'p', text: "You're showing more access, but still not everything. Let them want more." },
      { type: 'h3', text: 'Step 3: Private Tease (DMs)' },
      { type: 'p', text: "Once they're on Snap, it's time to build one-on-one energy. You're replying to messages, reacting to theirs, teasing a little, giving attention without giving it all away." },
      { type: 'p', text: '"Damn, you\'re cute." "I actually post way more on my secret page but not everyone gets it 👀" "Only if you really wanna see it…"' },
      { type: 'p', text: "You're not spamming a link. You're making it feel like a private offer. An invite. A secret. That's when they ask: \"Where's the link?\" And now they're ready." },
      { type: 'h3', text: 'Step 4: Premium Access (OnlyFans)' },
      { type: 'p', text: "This is the final step — the conversion. You've filtered out the cold, broke, or creepy ones. The men (or women) who make it here are: Emotionally invested, Curious about your full content, Feeling like they're special for getting access" },
      { type: 'p', text: "Now your OnlyFans isn't just porn — it's exclusive access to someone they already feel connected to. This turns a $10 sub into: $50 in tips, $200 in custom requests, A long-term paying relationship" },
      { type: 'h3', text: 'This Funnel Works Because:' },
      { type: 'p', text: "It's layered. Each step makes them want more. It's classy. You're not desperate — you're exclusive. It's scalable. The top of your funnel (YouTube/IG) brings in hundreds. Your DMs filter the real buyers." },
      { type: 'p', text: "Most creators dump their OnlyFans link in bio and pray. You're building a machine that turns attention into obsession — and obsession into income." },
    ],
  },
  {
    id: 'character-aesthetic',
    number: 4,
    title: 'Crafting Your Character & Aesthetic',
    subtitle: 'Learn how to develop a unique character and aesthetic that attracts your ideal audience and sets you apart.',
    takeaways: [
      'Identify and amplify your unique qualities to build your character',
      "Create a cohesive aesthetic that's instantly recognizable",
      'Maintain consistency across all platforms while staying authentic',
    ],
    blocks: [
      { type: 'blockquote', text: "You're not selling your body — you're selling your vibe." },
      { type: 'p', text: "Let's be real: There are millions of hot girls and sexy guys online. But the ones who stand out? They don't just post nudes. They build personas." },
      { type: 'p', text: "Think of the Kardashians again. They aren't famous because of talent. They're famous because you feel like you know them. You know Kim's voice. Kylie's pout. Kourtney's dry sarcasm." },
      { type: 'p', text: 'Your brand isn\'t just your name — it\'s your character, your energy, and your aesthetic. This chapter helps you build that.' },
      { type: 'h3', text: 'Part 1: Define Your Character' },
      { type: 'p', text: "You're not faking — you're amplifying a real side of you that people obsess over. Ask yourself: What vibe do I naturally give off? What energy do people compliment me on? What version of me do people fall for?" },
      { type: 'p', text: 'Here are some example archetypes:' },
      { type: 'ul', items: ['The Innocent Babe: Sweet, soft-spoken, blushy, "just curious"', 'The Glam Queen: Confident, flashy, designer outfits, heels', 'The Hot Tomboy: Chill, funny, into sneakers or gaming', 'The Mysterious Muse: Quiet, sultry, distant eyes, soft voice', 'The Fitness Baddie: Fit, healthy, leggings, gym vlogs', 'The Rich Tease: "You couldn\'t afford me" luxury energy', 'The Girl Next Door: Relatable, low-key sexy, candid vibe'] },
      { type: 'p', text: 'Pick 1–2 that feel most like you — and build your brand from there.' },
      { type: 'p', text: "Tip: You don't have to be over the top. You just need to be consistent." },
      { type: 'h3', text: 'Part 2: Choose Your Aesthetic' },
      { type: 'p', text: 'Once you have your character, your visual world should match. Aesthetic = colors, fonts, music, filters, captions, emojis, locations, and camera angles.' },
      { type: 'p', text: 'Some aesthetic examples:' },
      { type: 'ul', items: ['Warm & Soft: Golden hour light, fuzzy sweaters, handwritten fonts, blush tones', 'Dark & Luxurious: Black backgrounds, red lips, candlelight, luxury brands', 'Vibrant & Bold: Neon signs, colorful outfits, energetic captions', 'Natural & Earthy: Plants, clean skin, coffee shops, minimal makeup', 'Cute & Playful: Pink, plushies, sparkles, baby talk'] },
      { type: 'p', text: 'Now match your: Outfits, IG grid layout, YouTube thumbnails, Emoji use, Music choices, Even your Snapchat Bitmoji' },
      { type: 'p', text: "This makes your world feel real. Like stepping into a vibe they never want to leave." },
      { type: 'h3', text: 'Part 3: Stick to the Script (Without Being Fake)' },
      { type: 'p', text: 'Consistency builds trust. When people land on your page, they should instantly know what they\'re getting — emotionally and visually.' },
      { type: 'p', text: 'This doesn\'t mean acting fake. It means: Using similar lighting and filter styles, Maintaining your "voice" in captions and stories, Using specific phrases or emojis that become yours, Showing repeat moments (ex: always going to the same café)' },
      { type: 'h3', text: 'Why This Works' },
      { type: 'p', text: 'People fall in love with personalities, not just bodies. Vibes are addictive — consistency builds obsession. You become memorable — which drives higher retention & tips. You stand out in a market full of copy-paste creators' },
      { type: 'p', text: "You're not trying to be everyone. You're becoming someone — and people pay for that. You're crafting a cinematic experience. Your personal vlog becomes your reality show. And people binge that." },
      { type: 'h3', text: 'Mini Exercise: Build Your Brand Identity' },
      { type: 'p', text: 'Write this out now: My vibe: _______, My archetype(s): _______, My aesthetic keywords: _______, My PG-13 content ideas: _______, My Snapchat tone: _______' },
      { type: 'p', text: "This becomes your creative cheat sheet. Keep it open when filming content, writing captions, or editing reels." },
    ],
  },
  {
    id: 'content-strategy',
    number: 5,
    title: 'Your Content Strategy – What to Post & Where',
    subtitle: 'Master the art of content creation with a strategic approach to what you post and where you post it.',
    takeaways: [
      "Tailor content to each platform's unique culture and audience",
      'Use Instagram for brand showcase, TikTok for discovery, Twitter for conversation',
      'Snapchat serves as the bridge between free and paid content',
    ],
    blocks: [
      { type: 'blockquote', text: "Content isn't king — intentional content is." },
      { type: 'p', text: "At this stage, you've built your character, defined your aesthetic, and know what kind of vibe you're giving off. Now it's time to get strategic with your content. The goal isn't to \"go viral\" — it's to create magnetic, binge-worthy content that brings followers closer and closer to your private world — without ever mentioning OnlyFans." },
      { type: 'p', text: "You're building a social media funnel that slowly turns viewers into obsessed fans." },
      { type: 'h3', text: 'The Funnel Strategy in 3 Stages' },
      { type: 'p', text: 'Think of your content like dating:' },
      { type: 'ul', items: ['YouTube = First Date: Let them get to know you', 'Instagram = Flirting: Show beauty, style, and energy', 'Facebook = Passive Lure: Appear relatable, engage older audiences', 'Snapchat = Private Invite: Give the fantasy (sexy, unfiltered)', 'OnlyFans = Bedroom: Full access – but only once they earn it'] },
      { type: 'h3', text: 'YouTube: Your Reality Show' },
      { type: 'p', text: 'Post long-form vlog-style content that shows you living your life. No sexual content. No mention of OnlyFans. Just you being you — coffee shops, gym days, shopping hauls, get ready with me, storytimes.' },
      { type: 'p', text: 'Why? Builds parasocial connection, Establishes your personality, Attracts viewers who value more than your body, Content lives forever (evergreen)' },
      { type: 'p', text: 'Post ideas: "A Day in My Life as a 23-Year-Old Living Alone", "Come With Me to My Fave Coffee Spot", "My Night Routine + 3AM Thoughts"' },
      { type: 'p', text: 'Add CTAs like "Add me on Snap for more" at the end. That\'s where the funnel continues.' },
      { type: 'h3', text: 'Instagram: Your Digital Magazine' },
      { type: 'p', text: 'This is your aesthetic hub. Think of it as your personal Vogue — curated, pretty, and desirable.' },
      { type: 'p', text: 'High-quality photos, Outfit of the day (OOTD), Reels: funny moments, glam up, behind-the-scenes of your YouTube shoot, Stories: daily moments with vibes and emojis, minimal words' },
      { type: 'p', text: 'Why Instagram? You stay visible with Reels and Stories, Great for reaching new viewers and triggering FOMO, Shows you\'re real, gorgeous, and living a dream life' },
      { type: 'p', text: 'Never mention OnlyFans — ever. That kills reach.' },
      { type: 'h3', text: 'Facebook: The Unexpected Weapon' },
      { type: 'p', text: 'Yes, Facebook. Especially for creators targeting men 25+. It\'s underused and overpowered.' },
      { type: 'p', text: 'Post your YouTube video thumbnails with a link, Share IG reels as native videos, Join local city groups and subtly post selfies or lifestyle updates, Use comments wisely (especially on trending or viral posts)' },
      { type: 'p', text: "This builds slow-burn interest. And trust me — men stalk profiles. Give them something to get curious about." },
      { type: 'h3', text: 'Snapchat: The Secret Chamber' },
      { type: 'p', text: "We'll dive deeper in Chapter 6, but for now — know this: Snapchat is where your PG-13 brand becomes PG-17. More suggestive photos. More skin. Still no nudity — just intimacy." },
      { type: 'p', text: 'This is where your fans start thinking: "Maybe she is a little wild... Maybe there\'s more." And once they\'re addicted to your Snaps, then they\'ll ask about your OnlyFans — and that\'s when you send them a DM link.' },
      { type: 'h3', text: 'Summary: What to Post & Where' },
      { type: 'ul', items: ['YouTube: Story-driven vlogs. Let them fall for your personality. Document, don\'t create.', 'Instagram: High-aesthetic snapshots. Make them crave your world.', 'Facebook: Relatable + subtle attention. Let them discover you.', 'Snapchat: Intimate access. PG-17 previews. Quietly build desire.', 'OnlyFans: You don\'t promote it. You earn the right to send it.'] },
    ],
  },
  {
    id: 'snapchat-honeytrap',
    number: 6,
    title: 'Building the Snapchat Honeytrap',
    subtitle: 'Learn how to use Snapchat strategically to build deeper connections and guide followers toward your OnlyFans.',
    takeaways: [
      'Snapchat creates a sense of exclusivity and intimacy',
      'Use behind-the-scenes, authentic content to build connections',
      'Gradually escalate content to create desire for OnlyFans',
    ],
    blocks: [
      { type: 'blockquote', text: "The thirst trap isn't the goal. The honeytrap is. A slow, sweet drip that turns strangers into obsessed fans." },
      { type: 'p', text: 'Your job: Turn your Snapchat into a slow seduction — not a flood of nudes. The goal isn\'t to satisfy. It\'s to stimulate.' },
      { type: 'p', text: "By now, your public content is doing its job. You're not selling — you're attracting. You've positioned yourself as someone desirable, interesting, and just out of reach. Now it's time to let them feel like they're getting closer." },
      { type: 'p', text: "Welcome to Snapchat — the hidden tunnel from your public persona to your OnlyFans subscriber list. This chapter is your playbook for turning Snapchat into your most powerful sales funnel — without ever publicly promoting your OnlyFans." },
      { type: 'h3', text: 'Why Snapchat?' },
      { type: 'p', text: "Snapchat works because it feels personal. Unlike Instagram or YouTube, it gives your audience the illusion that they've been invited into your inner circle. It's private, fast, and emotionally triggering — and that's exactly what you want." },
      { type: 'p', text: 'Key benefits: Feels exclusive: Not everyone gets access. Feels unfiltered: You\'re not performing; you\'re revealing. No algorithm: Everyone sees your posts in order. Builds obsession: They check daily, fearing they\'ll miss something spicy.' },
      { type: 'h3', text: 'How the Snapchat Funnel Works' },
      { type: 'ul', items: ['Public Platforms (YouTube, IG, FB): Build curiosity and emotional interest through PG-13 lifestyle content. No nudity, no sexual captions, no mention of OnlyFans.', 'Call-to-Action: "Add me on Snap 👻" Always drop your Snap handle casually: in your IG bio, YouTube video description, or even spoken in a vlog. Example: "If you wanna see more of what I\'m like off-camera, add me on Snap 👻"', 'Snapchat (PG-17 Content): Post suggestive stories that feel personal: Bed selfies, Lingerie "just chilling" snaps, Flirty captions like "bored… guess what I\'m not wearing 😉", POV videos in bed, whispering or talking softly', 'Private Chat (DMs): Once they\'ve watched for a few days, they\'ll reach out. Don\'t link OnlyFans immediately. Tease. Play. Let them ask for more. Only then do you send your OF link — privately.'] },
      { type: 'h3', text: 'What to Post on Snapchat' },
      { type: 'p', text: "Keep it intimate, real, and almost explicit. Here's a content framework:" },
      { type: 'ul', items: ['Daily POVs: "Just woke up, come cuddle ☁️", brushing teeth in tank top — Soft, relatable', 'Outfit Checks: "Can I wear this out or is it too much?" — Playful, flirty', 'Voice Notes: Whisper "I had a dream about you…" — Auditory turn-on', 'Mirror Snaps: Lingerie, sheer tops, no face selfies — Suggestive, mysterious', '"Oops" Moments: "Did I just flash you? 😳" (but you didn\'t… or did you?) — Bait and tease', 'Behind the Scenes: "Filming something spicy for someone special…" — Mystery, scarcity'] },
      { type: 'p', text: "You're not giving them what they want — you're giving them just enough to crave more." },
      { type: 'h3', text: "Rules to Follow (So You Don't Get Banned)" },
      { type: 'p', text: "Snapchat allows more freedom than IG or FB, but you still need to be smart:" },
      { type: 'ul', items: ["Don't post full nudity in stories. Save that for direct messages or your OnlyFans content.", "Don't say \"subscribe to my OnlyFans\" Snapchat could ban your account if you're selling adult content directly. Never link OF in your public Snap story. Only send links in 1-on-1 chats after they ask.", "Don't mass spam. Be a real person. Reply like a friend, not a bot."] },
      { type: 'h3', text: 'How to Convert a Fan into a Buyer' },
      { type: 'p', text: "Here's a 3-message script to turn a Snap fan into a paying subscriber:" },
      { type: 'p', text: 'Wait for them to message you first. Example: "You\'re so fine fr 🔥"' },
      { type: 'p', text: 'You: "You\'re cute. You\'d go crazy if you saw what I can\'t post here 😘"' },
      { type: 'p', text: 'Let them ask for more. Them: "You got something more private?"' },
      { type: 'p', text: 'You: "Maybe… depends how curious you really are. 😈"' },
      { type: 'p', text: 'Then drop the link — but make it feel earned: "You seem cool. Don\'t tell anyone I sent this [OnlyFans link] 👉"' },
      { type: 'p', text: "This way, they feel chosen — and people pay more when they feel like they were the one who found you." },
      { type: 'h3', text: 'Pro Tip: Scarcity = Obsession' },
      { type: 'p', text: 'Use Snap to create urgency. Try things like: "Might delete this later… 👀", "Only up for 1 hour 💋", "Don\'t save this or I\'ll block you 💋"' },
      { type: 'p', text: "This gets people addicted to checking your stories every day." },
      { type: 'h3', text: 'Recap' },
      { type: 'p', text: "Snapchat is your PG-17 seduction layer in the funnel. Don't push your OnlyFans — pull them deeper. Post content that feels personal, unfiltered, and almost naughty. Use DMs as your conversion point. Let them ask first. Keep it sexy, smart, and strategic." },
    ],
  },
  {
    id: 'convert-without-selling',
    number: 7,
    title: "How to Convert Your Fans Without Ever Saying 'OnlyFans'",
    subtitle: 'Master the art of subtle conversion—turning followers into subscribers without ever being pushy or salesy.',
    takeaways: [
      'Build desire and curiosity rather than explicitly promoting',
      'Create strategic FOMO to drive subscriptions',
      'Focus on building relationships, not making sales',
    ],
    blocks: [
      { type: 'blockquote', text: 'The strongest sales pitch is the one they never realize happened.' },
      { type: 'p', text: "The top personal brands in adult content — whether it's softcore or full-blown explicit — don't sell their content. They seduce. They create a world you want to be part of. And that world always leads… quietly… to the cash register." },
      { type: 'p', text: 'In this chapter, you\'ll learn how to turn fans into buyers without ever uttering the words "OnlyFans" in public — and why that subtlety matters more than ever.' },
      { type: 'h3', text: 'The Psychology of the "Unspoken Offer"' },
      { type: 'p', text: "Let's break down what's actually happening in the mind of your audience:" },
      { type: 'ul', items: ['They see you on IG, YouTube, or Facebook — living life, looking amazing, not selling anything.', 'They notice your confidence and style, the way you speak, smile, and move.', 'They get curious. "Is she single?" "What else does she post?" "Is there more to this?"', 'They follow your Snap, where things feel more personal, intimate, maybe even dangerous.', 'They send a message. "You\'re stunning."', "You hint at something more... but never offer it.", 'They ask for it. And you give it… privately.'] },
      { type: 'p', text: "That's the game." },
      { type: 'h3', text: 'Why Being Subtle Sells More' },
      { type: 'p', text: 'Your goal is to create a "safe for work" persona that draws people in emotionally and visually — without ever signaling that you\'re selling adult content.' },
      { type: 'p', text: "Here's why subtlety wins:" },
      { type: 'ul', items: ['Platform safety: You won\'t get flagged or shadowbanned.', 'Psychological tension: People want what they can\'t have.', 'Mainstream appeal: You can grow a massive fan base without scaring off casual viewers.', 'Higher quality leads: The more someone invests emotionally, the more likely they\'ll pay.'] },
      { type: 'h3', text: 'Your Content Funnel — With Zero Mentions of OnlyFans' },
      { type: 'ul', items: ['YouTube: Lifestyle vlogs, "Day in my life," gym, dating stories — Build personality, trust, curiosity', 'Instagram: High-quality flirty photos, casual captions, no nudity — Visual hook, maintain PG public image', 'Facebook: Cross-posted reels/clips from YouTube, nostalgic personal updates — Reach older male demo, feel relatable', 'Snapchat: Suggestive POV content, mirror selfies, subtle seduction — Create emotional tension and obsession', 'DMs: Casual responses, subtle teases, slow reveals, private links — Convert attention into purchases'] },
      { type: 'h3', text: 'Conversion Scripts (Without Mentioning OnlyFans)' },
      { type: 'p', text: 'When They DM You on Snapchat or Instagram:' },
      { type: 'p', text: 'Them: "You\'re literally the hottest girl on here."' },
      { type: 'p', text: 'You: "That\'s sweet. You\'d lose your mind if you saw the side of me I can\'t show here 😘"' },
      { type: 'p', text: 'Them: "Do you post anything more private?"' },
      { type: 'p', text: 'You: "Maybe… but not for everyone. I like keeping things a little more personal."' },
      { type: 'p', text: 'Them: "You got a private page or something?"' },
      { type: 'p', text: 'You: "I might. But only if I trust you 😉 want to find out?"' },
      { type: 'p', text: 'Then and only then — drop your OnlyFans link privately.' },
      { type: 'p', text: 'The goal is to make it feel exclusive — like they earned it.' },
      { type: 'p', text: 'At no point do you ever say: "Subscribe to my OnlyFans", "I have explicit content", "Buy my nudes"' },
      { type: 'p', text: 'Instead, everything is invitation-only.' },
      { type: 'h3', text: 'Scarcity = Status' },
      { type: 'p', text: 'People want what others can\'t get. Try these subtle tactics:' },
      { type: 'ul', items: ['Delay sending your link: Make them feel chosen.', "Don't send it to everyone: Say \"I don't share this with just anyone.\"", '"I might close my private page soon." Even if you won\'t.'] },
      { type: 'p', text: 'Make your audience feel like insiders — not customers.' },
      { type: 'h3', text: 'The High-Value Persona Formula' },
      { type: 'p', text: 'To take your brand from "hot girl" to "obsession," build this persona:' },
      { type: 'ul', items: ['In public: You\'re mysterious, stylish, and slightly flirty — like a celebrity they want to know more about.', 'In private (Snap): You\'re suggestive, playful, emotionally present.', 'In DMs: You\'re slightly hard to get, never desperate, always in control.'] },
      { type: 'p', text: "This is the difference between a $5 subscriber… and a $500 tipper." },
      { type: 'h3', text: 'Recap' },
      { type: 'p', text: "Selling without selling is about suggestion and seduction. Never mention your adult content publicly. Create tension and emotional desire through subtle content and scarcity. Let them ask for your OnlyFans. Then, and only then, give them the link in DMs. The best personal brands pull — they don't push." },
    ],
  },
];
